# Generated by Django 6.0.5 on 2026-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='file_name')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'XLSX'), ('csv', 'CSV')], verbose_name='file_type')),
                ('file_size', models.BinaryField(verbose_name='file_size')),
                ('seaweed_file_id', models.CharField(max_length=255, unique=True, verbose_name='seaweed_file_id')),
                ('file_content', models.CharField(verbose_name='file_content')),
                ('currency_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_type', models.CharField(default='BRL', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
