# Generated by Django 6.0.6 on 2026-06-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values_extraction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmodel',
            name='currency_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='file_content',
            field=models.TextField(blank=True, null=True, verbose_name='file_content'),
        ),
        # bytea → integer requer DROP + ADD porque o PostgreSQL não aceita USING bytea::integer
        migrations.RunSQL(
            sql="ALTER TABLE values_extraction_documentmodel DROP COLUMN file_size",
            reverse_sql="ALTER TABLE values_extraction_documentmodel ADD COLUMN file_size bytea NOT NULL DEFAULT ''",
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='file_size',
            field=models.PositiveIntegerField(verbose_name='file_size', default=0),
            preserve_default=False,
        ),
    ]
